export default {

  PROFILE_CREATED: 'PROFILE_CREATED',
  USER_LOGGED_IN: 'USER_LOGGED_IN',

  TASKS_RECEIVED: 'TASKS_RECEIVED',
  TASK_CREATED: 'TASK_CREATED',

  CATEGORY_SELECTED: 'CATEGORY_SELECTED'

}