export default {

  PROFILE_CREATED: 'PROFILE_CREATED',
  PROFILE_RECEIVED: 'PROFILE_RECEIVED',
  USER_LOGGED_IN: 'USER_LOGGED_IN',

  TASKS_RECEIVED: 'TASKS_RECEIVED',
  TASK_CREATED: 'TASK_CREATED',

  MESSAGE_CREATED: 'MESSAGE_CREATED',
  MESSAGES_RECEIVED: 'MESSAGES_RECEIVED',

  CATEGORY_SELECTED: 'CATEGORY_SELECTED'

}